### PR TITLE
Hellfire Citadel - Blood Furnace

### PR DESCRIPTION
**Pull request by Tobschinski**
The whole place was a complete mess (no offense), there is no point in simply fixing things, I prefer a complete work from scratch.

+ 139 creatures were removed, 208 got added
+ +4 creature_movement

-----

https://report.nostalrius.org/plugins/tracker/?tracker=30

### CODE REVIEW

**Comment by Tobschinski** [comment]
Please do not merge this commit yet, it will probably break the script of the second boss. But I want you  to have more time to review things.

**Comment by Tobschinski** [comment]
To do: 
+ fix templates, a lot of them have bad data
+ add waypoints to moving formations (requires core update first)
+ fix script of 2nd boss
+ re-calculate basedamage-values and assign proper multipliers
+ add creature_addon for cosmetic reasons

**Comment by DevDaemon** [comment]
Thank you for the work!
Tell me when I can merge, or if you need additional Core features to be able to do some scripts (EventAI actions, ...).

**Comment by DevDaemon** [comment]
If your commit is ready, please modify the "XXXX" to real numbers :)

**Comment by Tobschinski** [comment]
Uhm, I'd really like to finish at least the movement first. But that is kinda pointless with mangos' inferior version of moving formations.

**Comment by DevDaemon** [comment]
Just create the movement for the leader, and we will add formation movements when the core will support it.

**Comment by joao-fidalgo** [comment]
Couldn't this be implemented using Eluna ?

**Comment by DevDaemon** [comment]
The formation system is really something generic, and that should be a Core / C++ system.

**Pull request merged**
